[package]
name = "mp"
version = "0.1.0"
edition = "2024"

[dependencies]
bevy = { version = "0.17.2", features = ["dynamic_linking"] }
bevy_replicon = "0.36.0"
bevy_replicon_renet = "0.12"
renet = "1.2.0"
renet_netcode = "1.2.0"
serde = "1.0"
